#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirlineTicketsBooking
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Baza")]
	public partial class BazaDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertAvioKompanija(AvioKompanija instance);
    partial void UpdateAvioKompanija(AvioKompanija instance);
    partial void DeleteAvioKompanija(AvioKompanija instance);
    partial void InsertKorisnik(Korisnik instance);
    partial void UpdateKorisnik(Korisnik instance);
    partial void DeleteKorisnik(Korisnik instance);
    partial void InsertLet(Let instance);
    partial void UpdateLet(Let instance);
    partial void DeleteLet(Let instance);
    partial void InsertRezervacija(Rezervacija instance);
    partial void UpdateRezervacija(Rezervacija instance);
    partial void DeleteRezervacija(Rezervacija instance);
    #endregion
		
		public BazaDataContext() : 
				base(global::AirlineTicketsBooking.Properties.Settings.Default.BazaConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public BazaDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BazaDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BazaDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BazaDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<AvioKompanija> AvioKompanijas
		{
			get
			{
				return this.GetTable<AvioKompanija>();
			}
		}
		
		public System.Data.Linq.Table<Korisnik> Korisniks
		{
			get
			{
				return this.GetTable<Korisnik>();
			}
		}
		
		public System.Data.Linq.Table<Let> Lets
		{
			get
			{
				return this.GetTable<Let>();
			}
		}
		
		public System.Data.Linq.Table<Rezervacija> Rezervacijas
		{
			get
			{
				return this.GetTable<Rezervacija>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AvioKompanija")]
	public partial class AvioKompanija : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _NazivAvioKompanije;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnNazivAvioKompanijeChanging(string value);
    partial void OnNazivAvioKompanijeChanged();
    #endregion
		
		public AvioKompanija()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NazivAvioKompanije", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string NazivAvioKompanije
		{
			get
			{
				return this._NazivAvioKompanije;
			}
			set
			{
				if ((this._NazivAvioKompanije != value))
				{
					this.OnNazivAvioKompanijeChanging(value);
					this.SendPropertyChanging();
					this._NazivAvioKompanije = value;
					this.SendPropertyChanged("NazivAvioKompanije");
					this.OnNazivAvioKompanijeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Korisnik")]
	public partial class Korisnik : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _ImePrezime;
		
		private string _Username;
		
		private string _Password;
		
		private string _Email;
		
		private int _Telefon;
		
		private string _Adresa;
		
		private string _Grad;
		
		private string _Drzava;
		
		private string _Rank;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnImePrezimeChanging(string value);
    partial void OnImePrezimeChanged();
    partial void OnUsernameChanging(string value);
    partial void OnUsernameChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnTelefonChanging(int value);
    partial void OnTelefonChanged();
    partial void OnAdresaChanging(string value);
    partial void OnAdresaChanged();
    partial void OnGradChanging(string value);
    partial void OnGradChanged();
    partial void OnDrzavaChanging(string value);
    partial void OnDrzavaChanged();
    partial void OnRankChanging(string value);
    partial void OnRankChanged();
    #endregion
		
		public Korisnik()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ImePrezime", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string ImePrezime
		{
			get
			{
				return this._ImePrezime;
			}
			set
			{
				if ((this._ImePrezime != value))
				{
					this.OnImePrezimeChanging(value);
					this.SendPropertyChanging();
					this._ImePrezime = value;
					this.SendPropertyChanged("ImePrezime");
					this.OnImePrezimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				if ((this._Username != value))
				{
					this.OnUsernameChanging(value);
					this.SendPropertyChanging();
					this._Username = value;
					this.SendPropertyChanged("Username");
					this.OnUsernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefon", DbType="Int NOT NULL")]
		public int Telefon
		{
			get
			{
				return this._Telefon;
			}
			set
			{
				if ((this._Telefon != value))
				{
					this.OnTelefonChanging(value);
					this.SendPropertyChanging();
					this._Telefon = value;
					this.SendPropertyChanged("Telefon");
					this.OnTelefonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Adresa", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Adresa
		{
			get
			{
				return this._Adresa;
			}
			set
			{
				if ((this._Adresa != value))
				{
					this.OnAdresaChanging(value);
					this.SendPropertyChanging();
					this._Adresa = value;
					this.SendPropertyChanged("Adresa");
					this.OnAdresaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Grad", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Grad
		{
			get
			{
				return this._Grad;
			}
			set
			{
				if ((this._Grad != value))
				{
					this.OnGradChanging(value);
					this.SendPropertyChanging();
					this._Grad = value;
					this.SendPropertyChanged("Grad");
					this.OnGradChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Drzava", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Drzava
		{
			get
			{
				return this._Drzava;
			}
			set
			{
				if ((this._Drzava != value))
				{
					this.OnDrzavaChanging(value);
					this.SendPropertyChanging();
					this._Drzava = value;
					this.SendPropertyChanged("Drzava");
					this.OnDrzavaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rank", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Rank
		{
			get
			{
				return this._Rank;
			}
			set
			{
				if ((this._Rank != value))
				{
					this.OnRankChanging(value);
					this.SendPropertyChanging();
					this._Rank = value;
					this.SendPropertyChanged("Rank");
					this.OnRankChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Let")]
	public partial class Let : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private int _AKID;
		
		private int _LetBR;
		
		private int _SedistaPolazak;
		
		private int _SedistaPovratak;
		
		private string _PolazakDrzava;
		
		private string _PolazakGrad;
		
		private string _DestinacijaDrzava;
		
		private string _DestinacijaGrad;
		
		private string _Polazak;
		
		private string _PolazakDatum;
		
		private string _Dolazak;
		
		private string _DolazakDatum;
		
		private string _PovratakPolazakVreme;
		
		private string _PovratakPolazakDatum;
		
		private string _PovratakDolazakVreme;
		
		private string _PovratakDolazakDatum;
		
		private double _CenaEkonomska;
		
		private double _CenaBiznis;
		
		private double _CenaPrva;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnAKIDChanging(int value);
    partial void OnAKIDChanged();
    partial void OnLetBRChanging(int value);
    partial void OnLetBRChanged();
    partial void OnSedistaPolazakChanging(int value);
    partial void OnSedistaPolazakChanged();
    partial void OnSedistaPovratakChanging(int value);
    partial void OnSedistaPovratakChanged();
    partial void OnPolazakDrzavaChanging(string value);
    partial void OnPolazakDrzavaChanged();
    partial void OnPolazakGradChanging(string value);
    partial void OnPolazakGradChanged();
    partial void OnDestinacijaDrzavaChanging(string value);
    partial void OnDestinacijaDrzavaChanged();
    partial void OnDestinacijaGradChanging(string value);
    partial void OnDestinacijaGradChanged();
    partial void OnPolazakChanging(string value);
    partial void OnPolazakChanged();
    partial void OnPolazakDatumChanging(string value);
    partial void OnPolazakDatumChanged();
    partial void OnDolazakChanging(string value);
    partial void OnDolazakChanged();
    partial void OnDolazakDatumChanging(string value);
    partial void OnDolazakDatumChanged();
    partial void OnPovratakPolazakVremeChanging(string value);
    partial void OnPovratakPolazakVremeChanged();
    partial void OnPovratakPolazakDatumChanging(string value);
    partial void OnPovratakPolazakDatumChanged();
    partial void OnPovratakDolazakVremeChanging(string value);
    partial void OnPovratakDolazakVremeChanged();
    partial void OnPovratakDolazakDatumChanging(string value);
    partial void OnPovratakDolazakDatumChanged();
    partial void OnCenaEkonomskaChanging(double value);
    partial void OnCenaEkonomskaChanged();
    partial void OnCenaBiznisChanging(double value);
    partial void OnCenaBiznisChanged();
    partial void OnCenaPrvaChanging(double value);
    partial void OnCenaPrvaChanged();
    #endregion
		
		public Let()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AKID", DbType="Int NOT NULL")]
		public int AKID
		{
			get
			{
				return this._AKID;
			}
			set
			{
				if ((this._AKID != value))
				{
					this.OnAKIDChanging(value);
					this.SendPropertyChanging();
					this._AKID = value;
					this.SendPropertyChanged("AKID");
					this.OnAKIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LetBR", DbType="Int NOT NULL")]
		public int LetBR
		{
			get
			{
				return this._LetBR;
			}
			set
			{
				if ((this._LetBR != value))
				{
					this.OnLetBRChanging(value);
					this.SendPropertyChanging();
					this._LetBR = value;
					this.SendPropertyChanged("LetBR");
					this.OnLetBRChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SedistaPolazak", DbType="Int NOT NULL")]
		public int SedistaPolazak
		{
			get
			{
				return this._SedistaPolazak;
			}
			set
			{
				if ((this._SedistaPolazak != value))
				{
					this.OnSedistaPolazakChanging(value);
					this.SendPropertyChanging();
					this._SedistaPolazak = value;
					this.SendPropertyChanged("SedistaPolazak");
					this.OnSedistaPolazakChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SedistaPovratak", DbType="Int NOT NULL")]
		public int SedistaPovratak
		{
			get
			{
				return this._SedistaPovratak;
			}
			set
			{
				if ((this._SedistaPovratak != value))
				{
					this.OnSedistaPovratakChanging(value);
					this.SendPropertyChanging();
					this._SedistaPovratak = value;
					this.SendPropertyChanged("SedistaPovratak");
					this.OnSedistaPovratakChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PolazakDrzava", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string PolazakDrzava
		{
			get
			{
				return this._PolazakDrzava;
			}
			set
			{
				if ((this._PolazakDrzava != value))
				{
					this.OnPolazakDrzavaChanging(value);
					this.SendPropertyChanging();
					this._PolazakDrzava = value;
					this.SendPropertyChanged("PolazakDrzava");
					this.OnPolazakDrzavaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PolazakGrad", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string PolazakGrad
		{
			get
			{
				return this._PolazakGrad;
			}
			set
			{
				if ((this._PolazakGrad != value))
				{
					this.OnPolazakGradChanging(value);
					this.SendPropertyChanging();
					this._PolazakGrad = value;
					this.SendPropertyChanged("PolazakGrad");
					this.OnPolazakGradChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DestinacijaDrzava", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string DestinacijaDrzava
		{
			get
			{
				return this._DestinacijaDrzava;
			}
			set
			{
				if ((this._DestinacijaDrzava != value))
				{
					this.OnDestinacijaDrzavaChanging(value);
					this.SendPropertyChanging();
					this._DestinacijaDrzava = value;
					this.SendPropertyChanged("DestinacijaDrzava");
					this.OnDestinacijaDrzavaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DestinacijaGrad", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string DestinacijaGrad
		{
			get
			{
				return this._DestinacijaGrad;
			}
			set
			{
				if ((this._DestinacijaGrad != value))
				{
					this.OnDestinacijaGradChanging(value);
					this.SendPropertyChanging();
					this._DestinacijaGrad = value;
					this.SendPropertyChanged("DestinacijaGrad");
					this.OnDestinacijaGradChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Polazak", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Polazak
		{
			get
			{
				return this._Polazak;
			}
			set
			{
				if ((this._Polazak != value))
				{
					this.OnPolazakChanging(value);
					this.SendPropertyChanging();
					this._Polazak = value;
					this.SendPropertyChanged("Polazak");
					this.OnPolazakChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PolazakDatum", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string PolazakDatum
		{
			get
			{
				return this._PolazakDatum;
			}
			set
			{
				if ((this._PolazakDatum != value))
				{
					this.OnPolazakDatumChanging(value);
					this.SendPropertyChanging();
					this._PolazakDatum = value;
					this.SendPropertyChanged("PolazakDatum");
					this.OnPolazakDatumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dolazak", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Dolazak
		{
			get
			{
				return this._Dolazak;
			}
			set
			{
				if ((this._Dolazak != value))
				{
					this.OnDolazakChanging(value);
					this.SendPropertyChanging();
					this._Dolazak = value;
					this.SendPropertyChanged("Dolazak");
					this.OnDolazakChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DolazakDatum", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string DolazakDatum
		{
			get
			{
				return this._DolazakDatum;
			}
			set
			{
				if ((this._DolazakDatum != value))
				{
					this.OnDolazakDatumChanging(value);
					this.SendPropertyChanging();
					this._DolazakDatum = value;
					this.SendPropertyChanged("DolazakDatum");
					this.OnDolazakDatumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PovratakPolazakVreme", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string PovratakPolazakVreme
		{
			get
			{
				return this._PovratakPolazakVreme;
			}
			set
			{
				if ((this._PovratakPolazakVreme != value))
				{
					this.OnPovratakPolazakVremeChanging(value);
					this.SendPropertyChanging();
					this._PovratakPolazakVreme = value;
					this.SendPropertyChanged("PovratakPolazakVreme");
					this.OnPovratakPolazakVremeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PovratakPolazakDatum", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string PovratakPolazakDatum
		{
			get
			{
				return this._PovratakPolazakDatum;
			}
			set
			{
				if ((this._PovratakPolazakDatum != value))
				{
					this.OnPovratakPolazakDatumChanging(value);
					this.SendPropertyChanging();
					this._PovratakPolazakDatum = value;
					this.SendPropertyChanged("PovratakPolazakDatum");
					this.OnPovratakPolazakDatumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PovratakDolazakVreme", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string PovratakDolazakVreme
		{
			get
			{
				return this._PovratakDolazakVreme;
			}
			set
			{
				if ((this._PovratakDolazakVreme != value))
				{
					this.OnPovratakDolazakVremeChanging(value);
					this.SendPropertyChanging();
					this._PovratakDolazakVreme = value;
					this.SendPropertyChanged("PovratakDolazakVreme");
					this.OnPovratakDolazakVremeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PovratakDolazakDatum", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string PovratakDolazakDatum
		{
			get
			{
				return this._PovratakDolazakDatum;
			}
			set
			{
				if ((this._PovratakDolazakDatum != value))
				{
					this.OnPovratakDolazakDatumChanging(value);
					this.SendPropertyChanging();
					this._PovratakDolazakDatum = value;
					this.SendPropertyChanged("PovratakDolazakDatum");
					this.OnPovratakDolazakDatumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CenaEkonomska", DbType="Float NOT NULL")]
		public double CenaEkonomska
		{
			get
			{
				return this._CenaEkonomska;
			}
			set
			{
				if ((this._CenaEkonomska != value))
				{
					this.OnCenaEkonomskaChanging(value);
					this.SendPropertyChanging();
					this._CenaEkonomska = value;
					this.SendPropertyChanged("CenaEkonomska");
					this.OnCenaEkonomskaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CenaBiznis", DbType="Float NOT NULL")]
		public double CenaBiznis
		{
			get
			{
				return this._CenaBiznis;
			}
			set
			{
				if ((this._CenaBiznis != value))
				{
					this.OnCenaBiznisChanging(value);
					this.SendPropertyChanging();
					this._CenaBiznis = value;
					this.SendPropertyChanged("CenaBiznis");
					this.OnCenaBiznisChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CenaPrva", DbType="Float NOT NULL")]
		public double CenaPrva
		{
			get
			{
				return this._CenaPrva;
			}
			set
			{
				if ((this._CenaPrva != value))
				{
					this.OnCenaPrvaChanging(value);
					this.SendPropertyChanging();
					this._CenaPrva = value;
					this.SendPropertyChanged("CenaPrva");
					this.OnCenaPrvaChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Rezervacija")]
	public partial class Rezervacija : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private int _IDLeta;
		
		private int _IDKorisnika;
		
		private string _IPKorisnika;
		
		private int _AKID;
		
		private string _AKNaziv;
		
		private int _LetBR;
		
		private int _Sedista;
		
		private string _Klasa;
		
		private string _Karta;
		
		private string _PolazakDrzava;
		
		private string _PolazakGrad;
		
		private string _DestinacijaDrzava;
		
		private string _DestinacijaGrad;
		
		private string _Polazak;
		
		private string _PolazakDatum;
		
		private string _Dolazak;
		
		private string _DolazakDatum;
		
		private string _PovratakPolazakVreme;
		
		private string _PovratakPolazakDatum;
		
		private string _PovratakDolazakVreme;
		
		private string _PovratakDolazakDatum;
		
		private double _Cena;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnIDLetaChanging(int value);
    partial void OnIDLetaChanged();
    partial void OnIDKorisnikaChanging(int value);
    partial void OnIDKorisnikaChanged();
    partial void OnIPKorisnikaChanging(string value);
    partial void OnIPKorisnikaChanged();
    partial void OnAKIDChanging(int value);
    partial void OnAKIDChanged();
    partial void OnAKNazivChanging(string value);
    partial void OnAKNazivChanged();
    partial void OnLetBRChanging(int value);
    partial void OnLetBRChanged();
    partial void OnSedistaChanging(int value);
    partial void OnSedistaChanged();
    partial void OnKlasaChanging(string value);
    partial void OnKlasaChanged();
    partial void OnKartaChanging(string value);
    partial void OnKartaChanged();
    partial void OnPolazakDrzavaChanging(string value);
    partial void OnPolazakDrzavaChanged();
    partial void OnPolazakGradChanging(string value);
    partial void OnPolazakGradChanged();
    partial void OnDestinacijaDrzavaChanging(string value);
    partial void OnDestinacijaDrzavaChanged();
    partial void OnDestinacijaGradChanging(string value);
    partial void OnDestinacijaGradChanged();
    partial void OnPolazakChanging(string value);
    partial void OnPolazakChanged();
    partial void OnPolazakDatumChanging(string value);
    partial void OnPolazakDatumChanged();
    partial void OnDolazakChanging(string value);
    partial void OnDolazakChanged();
    partial void OnDolazakDatumChanging(string value);
    partial void OnDolazakDatumChanged();
    partial void OnPovratakPolazakVremeChanging(string value);
    partial void OnPovratakPolazakVremeChanged();
    partial void OnPovratakPolazakDatumChanging(string value);
    partial void OnPovratakPolazakDatumChanged();
    partial void OnPovratakDolazakVremeChanging(string value);
    partial void OnPovratakDolazakVremeChanged();
    partial void OnPovratakDolazakDatumChanging(string value);
    partial void OnPovratakDolazakDatumChanged();
    partial void OnCenaChanging(double value);
    partial void OnCenaChanged();
    #endregion
		
		public Rezervacija()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDLeta", DbType="Int NOT NULL")]
		public int IDLeta
		{
			get
			{
				return this._IDLeta;
			}
			set
			{
				if ((this._IDLeta != value))
				{
					this.OnIDLetaChanging(value);
					this.SendPropertyChanging();
					this._IDLeta = value;
					this.SendPropertyChanged("IDLeta");
					this.OnIDLetaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDKorisnika", DbType="Int NOT NULL")]
		public int IDKorisnika
		{
			get
			{
				return this._IDKorisnika;
			}
			set
			{
				if ((this._IDKorisnika != value))
				{
					this.OnIDKorisnikaChanging(value);
					this.SendPropertyChanging();
					this._IDKorisnika = value;
					this.SendPropertyChanged("IDKorisnika");
					this.OnIDKorisnikaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IPKorisnika", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string IPKorisnika
		{
			get
			{
				return this._IPKorisnika;
			}
			set
			{
				if ((this._IPKorisnika != value))
				{
					this.OnIPKorisnikaChanging(value);
					this.SendPropertyChanging();
					this._IPKorisnika = value;
					this.SendPropertyChanged("IPKorisnika");
					this.OnIPKorisnikaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AKID", DbType="Int NOT NULL")]
		public int AKID
		{
			get
			{
				return this._AKID;
			}
			set
			{
				if ((this._AKID != value))
				{
					this.OnAKIDChanging(value);
					this.SendPropertyChanging();
					this._AKID = value;
					this.SendPropertyChanged("AKID");
					this.OnAKIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AKNaziv", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string AKNaziv
		{
			get
			{
				return this._AKNaziv;
			}
			set
			{
				if ((this._AKNaziv != value))
				{
					this.OnAKNazivChanging(value);
					this.SendPropertyChanging();
					this._AKNaziv = value;
					this.SendPropertyChanged("AKNaziv");
					this.OnAKNazivChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LetBR", DbType="Int NOT NULL")]
		public int LetBR
		{
			get
			{
				return this._LetBR;
			}
			set
			{
				if ((this._LetBR != value))
				{
					this.OnLetBRChanging(value);
					this.SendPropertyChanging();
					this._LetBR = value;
					this.SendPropertyChanged("LetBR");
					this.OnLetBRChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sedista", DbType="Int NOT NULL")]
		public int Sedista
		{
			get
			{
				return this._Sedista;
			}
			set
			{
				if ((this._Sedista != value))
				{
					this.OnSedistaChanging(value);
					this.SendPropertyChanging();
					this._Sedista = value;
					this.SendPropertyChanged("Sedista");
					this.OnSedistaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Klasa", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Klasa
		{
			get
			{
				return this._Klasa;
			}
			set
			{
				if ((this._Klasa != value))
				{
					this.OnKlasaChanging(value);
					this.SendPropertyChanging();
					this._Klasa = value;
					this.SendPropertyChanged("Klasa");
					this.OnKlasaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Karta", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Karta
		{
			get
			{
				return this._Karta;
			}
			set
			{
				if ((this._Karta != value))
				{
					this.OnKartaChanging(value);
					this.SendPropertyChanging();
					this._Karta = value;
					this.SendPropertyChanged("Karta");
					this.OnKartaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PolazakDrzava", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string PolazakDrzava
		{
			get
			{
				return this._PolazakDrzava;
			}
			set
			{
				if ((this._PolazakDrzava != value))
				{
					this.OnPolazakDrzavaChanging(value);
					this.SendPropertyChanging();
					this._PolazakDrzava = value;
					this.SendPropertyChanged("PolazakDrzava");
					this.OnPolazakDrzavaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PolazakGrad", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string PolazakGrad
		{
			get
			{
				return this._PolazakGrad;
			}
			set
			{
				if ((this._PolazakGrad != value))
				{
					this.OnPolazakGradChanging(value);
					this.SendPropertyChanging();
					this._PolazakGrad = value;
					this.SendPropertyChanged("PolazakGrad");
					this.OnPolazakGradChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DestinacijaDrzava", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string DestinacijaDrzava
		{
			get
			{
				return this._DestinacijaDrzava;
			}
			set
			{
				if ((this._DestinacijaDrzava != value))
				{
					this.OnDestinacijaDrzavaChanging(value);
					this.SendPropertyChanging();
					this._DestinacijaDrzava = value;
					this.SendPropertyChanged("DestinacijaDrzava");
					this.OnDestinacijaDrzavaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DestinacijaGrad", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string DestinacijaGrad
		{
			get
			{
				return this._DestinacijaGrad;
			}
			set
			{
				if ((this._DestinacijaGrad != value))
				{
					this.OnDestinacijaGradChanging(value);
					this.SendPropertyChanging();
					this._DestinacijaGrad = value;
					this.SendPropertyChanged("DestinacijaGrad");
					this.OnDestinacijaGradChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Polazak", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Polazak
		{
			get
			{
				return this._Polazak;
			}
			set
			{
				if ((this._Polazak != value))
				{
					this.OnPolazakChanging(value);
					this.SendPropertyChanging();
					this._Polazak = value;
					this.SendPropertyChanged("Polazak");
					this.OnPolazakChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PolazakDatum", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string PolazakDatum
		{
			get
			{
				return this._PolazakDatum;
			}
			set
			{
				if ((this._PolazakDatum != value))
				{
					this.OnPolazakDatumChanging(value);
					this.SendPropertyChanging();
					this._PolazakDatum = value;
					this.SendPropertyChanged("PolazakDatum");
					this.OnPolazakDatumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dolazak", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Dolazak
		{
			get
			{
				return this._Dolazak;
			}
			set
			{
				if ((this._Dolazak != value))
				{
					this.OnDolazakChanging(value);
					this.SendPropertyChanging();
					this._Dolazak = value;
					this.SendPropertyChanged("Dolazak");
					this.OnDolazakChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DolazakDatum", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string DolazakDatum
		{
			get
			{
				return this._DolazakDatum;
			}
			set
			{
				if ((this._DolazakDatum != value))
				{
					this.OnDolazakDatumChanging(value);
					this.SendPropertyChanging();
					this._DolazakDatum = value;
					this.SendPropertyChanged("DolazakDatum");
					this.OnDolazakDatumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PovratakPolazakVreme", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string PovratakPolazakVreme
		{
			get
			{
				return this._PovratakPolazakVreme;
			}
			set
			{
				if ((this._PovratakPolazakVreme != value))
				{
					this.OnPovratakPolazakVremeChanging(value);
					this.SendPropertyChanging();
					this._PovratakPolazakVreme = value;
					this.SendPropertyChanged("PovratakPolazakVreme");
					this.OnPovratakPolazakVremeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PovratakPolazakDatum", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string PovratakPolazakDatum
		{
			get
			{
				return this._PovratakPolazakDatum;
			}
			set
			{
				if ((this._PovratakPolazakDatum != value))
				{
					this.OnPovratakPolazakDatumChanging(value);
					this.SendPropertyChanging();
					this._PovratakPolazakDatum = value;
					this.SendPropertyChanged("PovratakPolazakDatum");
					this.OnPovratakPolazakDatumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PovratakDolazakVreme", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string PovratakDolazakVreme
		{
			get
			{
				return this._PovratakDolazakVreme;
			}
			set
			{
				if ((this._PovratakDolazakVreme != value))
				{
					this.OnPovratakDolazakVremeChanging(value);
					this.SendPropertyChanging();
					this._PovratakDolazakVreme = value;
					this.SendPropertyChanged("PovratakDolazakVreme");
					this.OnPovratakDolazakVremeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PovratakDolazakDatum", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string PovratakDolazakDatum
		{
			get
			{
				return this._PovratakDolazakDatum;
			}
			set
			{
				if ((this._PovratakDolazakDatum != value))
				{
					this.OnPovratakDolazakDatumChanging(value);
					this.SendPropertyChanging();
					this._PovratakDolazakDatum = value;
					this.SendPropertyChanged("PovratakDolazakDatum");
					this.OnPovratakDolazakDatumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cena", DbType="Float NOT NULL")]
		public double Cena
		{
			get
			{
				return this._Cena;
			}
			set
			{
				if ((this._Cena != value))
				{
					this.OnCenaChanging(value);
					this.SendPropertyChanging();
					this._Cena = value;
					this.SendPropertyChanged("Cena");
					this.OnCenaChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
